[package]
name = "photo-library"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
clap = { version = "4", features = ["derive"] }
env_logger = "0.11.8"
indicatif = "0.18.3"
kamadak-exif = "0.6.1"
log = "0.4.29"
walkdir = "2"
